/**
 * Triglav API
 * Triglav API Reference
 *
 * OpenAPI spec version: 1.0.0
 * Contact: triglav_admin_my@dena.jp
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.triglav.client.api;

import io.triglav.client.ApiException;
import io.triglav.client.ErrorModel;
import io.triglav.client.MessageEachResponse;
import io.triglav.client.MessageRequest;
import io.triglav.client.BulkinsertResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MessagesApi
 */
public class MessagesApiTest {

    private final MessagesApi api = new MessagesApi();

    
    /**
     * 
     *
     * Fetch messages with HTTP POST method
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchMessagesTest() throws ApiException {
        Integer offset = null;
        Integer limit = null;
        String resourceUris = null;
        // List<MessageEachResponse> response = api.fetchMessages(offset, limit, resourceUris);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * List messages with HTTP GET method
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listMessagesTest() throws ApiException {
        Integer offset = null;
        Integer limit = null;
        String resourceUris = null;
        // List<MessageEachResponse> response = api.listMessages(offset, limit, resourceUris);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Enqueues new messages
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendMessagesTest() throws ApiException {
        List<MessageRequest> messages = null;
        // BulkinsertResponse response = api.sendMessages(messages);

        // TODO: test validations
    }
    
}
