/**
 * Triglav API
 * Triglav API Reference
 *
 * OpenAPI spec version: 1.0.0
 * Contact: triglav_admin_my@dena.jp
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.triglav.client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * MessageInput
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-07-28T19:01:01.009+09:00")
public class MessageInput   {
  @SerializedName("params")
  private String params = null;

  @SerializedName("payload")
  private String payload = null;

  public MessageInput params(String params) {
    this.params = params;
    return this;
  }

   /**
   * Any json string
   * @return params
  **/
  @ApiModelProperty(example = "null", value = "Any json string")
  public String getParams() {
    return params;
  }

  public void setParams(String params) {
    this.params = params;
  }

  public MessageInput payload(String payload) {
    this.payload = payload;
    return this;
  }

   /**
   * Any json string
   * @return payload
  **/
  @ApiModelProperty(example = "null", value = "Any json string")
  public String getPayload() {
    return payload;
  }

  public void setPayload(String payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageInput messageInput = (MessageInput) o;
    return Objects.equals(this.params, messageInput.params) &&
        Objects.equals(this.payload, messageInput.payload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(params, payload);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageInput {\n");
    
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

