/**
 * Triglav API
 * Triglav API Reference
 *
 * OpenAPI spec version: 1.0.0
 * Contact: triglav_admin_my@dena.jp
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.triglav.client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * JobMessageEachResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T19:53:17.612+09:00")
public class JobMessageEachResponse   {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("job_id")
  private Integer jobId = null;

  @SerializedName("time")
  private Integer time = null;

  @SerializedName("timezone")
  private String timezone = null;

  public JobMessageEachResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public JobMessageEachResponse jobId(Integer jobId) {
    this.jobId = jobId;
    return this;
  }

   /**
   * Job ID
   * @return jobId
  **/
  @ApiModelProperty(example = "null", value = "Job ID")
  public Integer getJobId() {
    return jobId;
  }

  public void setJobId(Integer jobId) {
    this.jobId = jobId;
  }

  public JobMessageEachResponse time(Integer time) {
    this.time = time;
    return this;
  }

   /**
   * Time of event in unix timestamp such as 1476025200 (2016-10-10 in +09:00)
   * @return time
  **/
  @ApiModelProperty(example = "null", value = "Time of event in unix timestamp such as 1476025200 (2016-10-10 in +09:00)")
  public Integer getTime() {
    return time;
  }

  public void setTime(Integer time) {
    this.time = time;
  }

  public JobMessageEachResponse timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Timezone of event time, that is, timezone of %Y-%m-%d for hdfs://path/to/%Y-%m-%d such as +09:00
   * @return timezone
  **/
  @ApiModelProperty(example = "null", value = "Timezone of event time, that is, timezone of %Y-%m-%d for hdfs://path/to/%Y-%m-%d such as +09:00")
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobMessageEachResponse jobMessageEachResponse = (JobMessageEachResponse) o;
    return Objects.equals(this.id, jobMessageEachResponse.id) &&
        Objects.equals(this.jobId, jobMessageEachResponse.jobId) &&
        Objects.equals(this.time, jobMessageEachResponse.time) &&
        Objects.equals(this.timezone, jobMessageEachResponse.timezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, jobId, time, timezone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobMessageEachResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

