/**
 * Triglav API
 * Triglav API Reference
 *
 * OpenAPI spec version: 1.0.0
 * Contact: triglav_admin_my@dena.jp
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.triglav.client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * MessageFetchRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-10T17:49:25.554+09:00")
public class MessageFetchRequest   {
  @SerializedName("offset")
  private Long offset = null;

  @SerializedName("limit")
  private Long limit = null;

  @SerializedName("resource_uris")
  private List<String> resourceUris = new ArrayList<String>();

  public MessageFetchRequest offset(Long offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Offset (Greater than or equal to) ID for Messages to fetch from
   * @return offset
  **/
  @ApiModelProperty(example = "null", required = true, value = "Offset (Greater than or equal to) ID for Messages to fetch from")
  public Long getOffset() {
    return offset;
  }

  public void setOffset(Long offset) {
    this.offset = offset;
  }

  public MessageFetchRequest limit(Long limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Number of limits
   * @return limit
  **/
  @ApiModelProperty(example = "null", value = "Number of limits")
  public Long getLimit() {
    return limit;
  }

  public void setLimit(Long limit) {
    this.limit = limit;
  }

  public MessageFetchRequest resourceUris(List<String> resourceUris) {
    this.resourceUris = resourceUris;
    return this;
  }

   /**
   * URIs of Resource
   * @return resourceUris
  **/
  @ApiModelProperty(example = "null", value = "URIs of Resource")
  public List<String> getResourceUris() {
    return resourceUris;
  }

  public void setResourceUris(List<String> resourceUris) {
    this.resourceUris = resourceUris;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageFetchRequest messageFetchRequest = (MessageFetchRequest) o;
    return Objects.equals(this.offset, messageFetchRequest.offset) &&
        Objects.equals(this.limit, messageFetchRequest.limit) &&
        Objects.equals(this.resourceUris, messageFetchRequest.resourceUris);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offset, limit, resourceUris);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageFetchRequest {\n");
    
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    resourceUris: ").append(toIndentedString(resourceUris)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

