/**
 * Triglav
 * Triglav API Reference.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.triglav.client.api;

import io.triglav.client.ApiException;
import io.triglav.client.User;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClustersApi
 */
public class ClustersApiTest {

    private final ClustersApi api = new ClustersApi();

    
    /**
     * Creates a new Cluster
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1ClustersCreateTest() throws ApiException {
        String name = null;
        String description = null;
        // api.apiV1ClustersCreate(name, description);

        // TODO: test validations
    }
    
    /**
     * Deletes an existing Cluster item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1ClustersDestroyTest() throws ApiException {
        Integer id = null;
        // api.apiV1ClustersDestroy(id);

        // TODO: test validations
    }
    
    /**
     * Fetches all Cluster items
     *
     * This lists all clusters
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1ClustersIndexTest() throws ApiException {
        // api.apiV1ClustersIndex();

        // TODO: test validations
    }
    
    /**
     * Fetches a single Cluster item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1ClustersShowTest() throws ApiException {
        Integer id = null;
        // User response = api.apiV1ClustersShow(id);

        // TODO: test validations
    }
    
    /**
     * Updates an existing Cluster
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1ClustersUpdateTest() throws ApiException {
        Integer id = null;
        String name = null;
        String description = null;
        // api.apiV1ClustersUpdate(id, name, description);

        // TODO: test validations
    }
    
}
