/**
 * Triglav API
 * Triglav API Reference
 *
 * OpenAPI spec version: 1.0.0
 * Contact: triglav_admin_my@dena.jp
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.triglav.client.api;

import io.triglav.client.ApiException;
import io.triglav.client.Job;
import io.triglav.client.JobInput;
import io.triglav.client.ErrorModel;
import io.triglav.client.JobEach;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for JobApi
 */
public class JobApiTest {

    private final JobApi api = new JobApi();

    
    /**
     * 
     *
     * Creates or Updates a single job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createOrUpdateJobTest() throws ApiException {
        JobInput job = null;
        // Job response = api.createOrUpdateJob(job);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Deletes single job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteJobByIdOrUriTest() throws ApiException {
        String idOrUri = null;
        // api.deleteJobByIdOrUri(idOrUri);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns a single job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findJobByIdOrUriTest() throws ApiException {
        String idOrUri = null;
        // Job response = api.findJobByIdOrUri(idOrUri);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns all jobs
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findJobsTest() throws ApiException {
        // List<JobEach> response = api.findJobs();

        // TODO: test validations
    }
    
}
