/**
 * Triglav
 * Triglav API Reference.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.triglav.client.api;

import io.triglav.client.ApiException;
import io.triglav.client.User;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * Creates a new User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1UsersCreateTest() throws ApiException {
        String name = null;
        String authenticator = null;
        List<Object> groups = null;
        String password = null;
        String description = null;
        String email = null;
        // api.apiV1UsersCreate(name, authenticator, groups, password, description, email);

        // TODO: test validations
    }
    
    /**
     * Deletes an existing User item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1UsersDestroyTest() throws ApiException {
        Integer id = null;
        // api.apiV1UsersDestroy(id);

        // TODO: test validations
    }
    
    /**
     * Fetches all User items
     *
     * This lists all the active users
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1UsersIndexTest() throws ApiException {
        // api.apiV1UsersIndex();

        // TODO: test validations
    }
    
    /**
     * Fetches a single User item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1UsersShowTest() throws ApiException {
        Integer id = null;
        // User response = api.apiV1UsersShow(id);

        // TODO: test validations
    }
    
    /**
     * Updates an existing User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiV1UsersUpdateTest() throws ApiException {
        Integer id = null;
        String name = null;
        String description = null;
        String authenticator = null;
        String email = null;
        List<Object> groups = null;
        String password = null;
        // api.apiV1UsersUpdate(id, name, description, authenticator, email, groups, password);

        // TODO: test validations
    }
    
}
