/**
 * Triglav API
 * Triglav API Reference
 *
 * OpenAPI spec version: 1.0.0
 * Contact: triglav_admin_my@dena.jp
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.github.triglav_dataflow.client.api;

import io.github.triglav_dataflow.client.ApiException;
import io.github.triglav_dataflow.client.JobRequest;
import io.github.triglav_dataflow.client.JobResponse;
import io.github.triglav_dataflow.client.ErrorModel;
import io.github.triglav_dataflow.client.JobEachResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for JobsApi
 */
public class JobsApiTest {

    private final JobsApi api = new JobsApi();

    
    /**
     * 
     *
     * Creates or Updates a single job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createOrUpdateJobTest() throws ApiException {
        JobRequest job = null;
        // JobResponse response = api.createOrUpdateJob(job);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Deletes single job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteJobTest() throws ApiException {
        String idOrUri = null;
        // api.deleteJob(idOrUri);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns a single job
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getJobTest() throws ApiException {
        String idOrUri = null;
        // JobResponse response = api.getJob(idOrUri);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns all jobs
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listJobsTest() throws ApiException {
        // List<JobEachResponse> response = api.listJobs();

        // TODO: test validations
    }
    
}
